/**
 * The canonical LinkedIn qualification flow as data.
 *
 * Message bodies are LOCKED copy approved by Robin (see docs/business/dm-flows/qualification-flow.md).
 * Do not rewrite them here. The brain only fills variables ({first_name}, {booking_link}) and, for
 * Q2 / the Q4 vocab-swap, a short Robin-voice read-back generated by the understanding layer.
 * Apostrophes are kept straight to match the approved copy verbatim.
 */
import type { FlowNode, FlowVars, FunnelStage, PortfolioValue } from './types.js';

export function fill(template: string, vars: FlowVars): string {
  return template
    .replaceAll('{first_name}', vars.firstName)
    .replaceAll('{booking_link}', vars.bookingLink)
    .replaceAll('{walkthrough_link}', vars.walkthroughLink);
}

/** Fixed-copy nodes (no read-back needed). Verbatim from the approved flow doc. */
export const FIXED_COPY: Partial<Record<FlowNode, string>> = {
  welcome:
    "Hi {first_name}, happy to share more on CGP. Before I do, I need to ask a few quick questions to see if it's the right fit?",
  objection_price:
    'Fair question. Pricing depends on which format fits your situation, which is what the four questions figure out. Should we run through them real quick?',
  q1: 'First one, how long have you been investing in crypto?',
  q3: 'Makes sense. Why that specifically?',
  q4: 'Last one. Roughly, how much do you have deployed in crypto right now, or planning to deploy?',
  pitch_call:
    "Based on those four answers, there's a potential for a fit.\n\nBest next step is a call. I'll analyze your strategy in more depth, and we will uncover what needs to change in order for you to manage your portfolio in the most professional way. After that, if it makes sense for you, I'll walk you through exactly how our system works, how work together would look like. So either way you walk away with clarity around your current investment situation.\n\nShould we book that call?",
  hesitant:
    'The call is assessment, not a pitch. We walk through your situation, I give you a clear read on whether CGP is the right move, and you decide from there.\n\nShould we book that call?',
  ask_email: "Alright, I'll set up the call. What's the best email for the calendar invite?",
  send_link: 'Here you go: {booking_link}\n\nBook any slot that works for you.',
  booking_reminder: 'Did you have any technical difficulties with the link?',
  value_touch:
    'Hi {first_name}, was reading through this walkthrough and thought it might be useful for you: {walkthrough_link}.\n\nWorth a look.',
  re_engage:
    "Glad it's useful. Saw we didn't continue the questions in regards to CGP. Let's pick them up where we stopped last time: How long have you been in crypto?",
  soft_close_low_capital:
    "Appreciate you going through those. To be honest: at that capital level, the program's format doesn't fit yet, the structure is built around a different range. I'll send you the free walkthrough instead, which is the better starting point: {walkthrough_link}.",
  disqualified: "CGP isn't the right fit for that situation.",
};

/** Q2 reads back the Q1 answer, then asks the locked question. */
export function q2Message(readback: string): string {
  const rb = readback.trim().replace(/\s+/g, ' ');
  return `${rb} What's the main thing you're trying to improve in how you manage your portfolio?`;
}

/** Q4 vocab-swap (Node 7b): acknowledge the confusion, swap deployed->invested, never explain. */
export function q4SwapMessage(readback: string): string {
  const rb = readback.trim().replace(/\s+/g, ' ');
  return `${rb} so how much do you have invested in crypto right now, or planning to invest?`;
}

/** Map a flow node to the DB funnel_stage for persistence + dashboards. */
export function nodeToStage(node: FlowNode): FunnelStage {
  switch (node) {
    case 'welcome':
      return 'opener_sent';
    case 'objection_price':
    case 'q1':
    case 'q2':
    case 'q3':
    case 'q4':
    case 're_engage':
      return 'qualifying';
    case 'pitch_call':
    case 'hesitant':
    case 'ask_email':
      return 'qualified';
    case 'send_link':
    case 'booking_reminder':
      return 'booking_offered';
    case 'booked':
      return 'booked';
    case 'disqualified':
      return 'disqualified';
    case 'value_touch':
    case 'parked':
    case 'soft_close_low_capital':
      return 'parked';
  }
}

export type CapitalTier = 'high' | 'mid' | 'low';

/**
 * Capital routing from Q4 (qualification-flow.md Node 7):
 * - high ($100k+)            -> pitch_call
 * - mid ($50k–$100k / vague) -> pitch_call, flag to human
 * - low (<$50k)              -> soft close, do not pitch
 */
export function capitalTier(pv: PortfolioValue | undefined): CapitalTier {
  switch (pv) {
    case '$100,000 - $250,000':
    case '$250,000 - $500,000':
    case '$500,000 - $1M':
    case 'Over $1M':
      return 'high';
    case '$50,000 - $100,000':
      return 'mid';
    case "I don't hold crypto yet":
    case 'Under $25,000':
    case '$25,000 - $50,000':
      return 'low';
    default:
      return 'mid'; // vague / unknown -> pitch but flag for human review
  }
}
